#!/usr/bin/env bash
set -euo pipefail

# HeySummon — Self-Hosting Installer
# ------------------------------------
# Downloads docker-compose.yml, generates required secrets, and starts HeySummon.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/thomasansems/heysummon/main/install.sh | bash
#
# Or download and run:
#   curl -O https://raw.githubusercontent.com/thomasansems/heysummon/main/install.sh
#   bash install.sh

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
BOLD='\033[1m'; NC='\033[0m'

info() { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()   { echo -e "${GREEN}✓${NC}  $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
die()  { echo -e "${RED}✗${NC}  $*" >&2; exit 1; }

REPO_RAW="https://raw.githubusercontent.com/thomasansems/heysummon/main"
INSTALL_DIR="${HEYSUMMON_DIR:-$HOME/.heysummon-docker}"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║         HeySummon Installer              ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Checks ───────────────────────────────────────────

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required. See https://docs.docker.com/compose/install/"
command -v openssl >/dev/null 2>&1 || die "openssl is required but not found."

# ── Install directory ────────────────────────────────

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Installing into: $INSTALL_DIR"

# ── Download compose file ────────────────────────────

if [[ -f docker-compose.yml ]]; then
  warn "docker-compose.yml already exists — skipping download (delete it to re-download)"
else
  info "Downloading docker-compose.yml..."
  curl -fsSL "$REPO_RAW/docker-compose.yml" -o docker-compose.yml
  ok "docker-compose.yml downloaded"
fi

# ── Generate .env ────────────────────────────────────

if [[ -f .env ]]; then
  warn ".env already exists — skipping secret generation (delete it to regenerate)"
else
  info "Generating secrets and writing .env..."

  NEXTAUTH_SECRET=$(openssl rand -hex 32)
  MERCURE_JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > .env <<EOF
# HeySummon — generated by installer on $(date -Iseconds)
# Edit this file to configure OAuth, tunnels, or change the public URL.

# ─── Required secrets (auto-generated) ──────────────
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}

# ─── Database ───────────────────────────────────────
DB_PASSWORD=${DB_PASSWORD}

# ─── URLs ───────────────────────────────────────────
# Change NEXTAUTH_URL to your public URL if using a tunnel.
NEXTAUTH_URL=http://localhost:3445
HEYSUMMON_PUBLIC_URL=http://localhost:3445

# ─── Auth ───────────────────────────────────────────
# Form login is enabled by default. No OAuth needed.
# ALLOW_REGISTRATION=true    # uncomment to allow more than one user to register

# ─── Tunnel (optional) ──────────────────────────────
# Uncomment one block and run: docker compose --profile <name> up -d

# Cloudflare:
# CLOUDFLARE_TUNNEL_TOKEN=

# Tailscale:
# TAILSCALE_AUTHKEY=

# Ngrok:
# NGROK_AUTHTOKEN=
# NGROK_DOMAIN=    # optional custom domain (paid plans)
EOF

  ok ".env created with generated secrets"
fi

# ── Start ────────────────────────────────────────────

echo ""
info "Starting HeySummon..."
docker compose up -d

echo ""
echo -e "${GREEN}${BOLD}HeySummon is running!${NC}"
echo ""
echo -e "  Dashboard:  ${BOLD}http://localhost:3445${NC}"
echo -e "  .env:       ${BOLD}${INSTALL_DIR}/.env${NC}"
echo ""
echo -e "${BLUE}Tip:${NC} The first user to sign up becomes the admin."
echo -e "${BLUE}Tip:${NC} To expose publicly, edit .env and run:"
echo -e "     ${BOLD}docker compose --profile ngrok up -d${NC}     (quick testing)"
echo -e "     ${BOLD}docker compose --profile cloudflare up -d${NC} (production)"
echo ""
echo -e "To stop:   ${BOLD}docker compose down${NC}"
echo -e "To update: ${BOLD}docker compose pull && docker compose up -d${NC}"
echo ""
