#!/usr/bin/env bash
set -euo pipefail

# HeySummon — Local Development Setup Wizard
# -------------------------------------------
# Interactive setup for local development. Generates .env.local, creates the
# database, and gets you ready to run `pnpm dev`.
#
# Usage:
#   bash install-local-dev.sh

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
BOLD='\033[1m'; NC='\033[0m'

info() { echo -e "${BLUE}i${NC}  $*"; }
ok()   { echo -e "${GREEN}✓${NC}  $*"; }
warn() { echo -e "${YELLOW}!${NC}  $*"; }
die()  { echo -e "${RED}x${NC}  $*" >&2; exit 1; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║      HeySummon — Local Dev Setup         ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Checks ───────────────────────────────────────────

command -v node >/dev/null 2>&1 || die "Node.js is not installed. See https://nodejs.org"
command -v pnpm >/dev/null 2>&1 || die "pnpm is not installed. Run: npm i -g pnpm@latest"

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if (( NODE_VERSION < 18 )); then
  die "Node.js 18+ required (found v${NODE_VERSION})"
fi

# ── Install dependencies ─────────────────────────────

if [[ ! -d node_modules ]] || [[ ! -f node_modules/.pnpm/lock.yaml ]]; then
  info "Installing dependencies..."
  pnpm install
  ok "Dependencies installed"
else
  ok "Dependencies already installed"
fi

# ── Setup wizard ─────────────────────────────────────

CONFIGURED_PORT="3425"

if [[ -f .env.local ]]; then
  warn ".env.local already exists -- skipping setup wizard (delete it to re-run)"
else
  echo -e "${BOLD}Setup Wizard${NC}"
  echo ""

  # 1. Port
  read -rp "Port for the dev server [3425]: " port_input
  CONFIGURED_PORT="${port_input:-3425}"
  echo ""

  # 2. Generate secrets
  info "Generating secrets..."

  if command -v openssl >/dev/null 2>&1; then
    NEXTAUTH_SECRET=$(openssl rand -hex 32)
  else
    # Fallback: use Node.js to generate secret
    NEXTAUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  fi

  # 3. Write .env.local (Next.js app config)
  cat > .env.local <<EOF
# HeySummon -- generated by install-local-dev.sh on $(date -Iseconds)

# ─── Required secrets (auto-generated) ──────────────
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# ─── URLs ───────────────────────────────────────────
NEXTAUTH_URL=http://localhost:${CONFIGURED_PORT}
HEYSUMMON_PUBLIC_URL=http://localhost:${CONFIGURED_PORT}

# ─── Port ───────────────────────────────────────────
PORT=${CONFIGURED_PORT}

# ─── Auth ───────────────────────────────────────────
# Form login is enabled by default. No OAuth needed.
ENABLE_FORM_LOGIN=true

# Allow multiple users to register (default: only first user)
# ALLOW_REGISTRATION=true

# ─── Edition ────────────────────────────────────────
HEYSUMMON_EDITION=community
EOF

  ok ".env.local created with generated secrets"
fi

# 4. Write .env (Prisma reads .env only, not .env.local)
if [[ ! -f .env ]]; then
  cat > .env <<EOF
# Prisma requires DATABASE_URL in .env (it does not read .env.local)
DATABASE_URL=file:./heysummon.db
EOF
  ok ".env created with DATABASE_URL for Prisma"
fi

# ── Database ─────────────────────────────────────────

info "Setting up database..."
pnpm exec prisma migrate dev --skip-generate 2>&1 | grep -E "^(Applying|Your database|SQLite)" || true
pnpm exec prisma generate 2>&1 | grep -E "Generated" || true
ok "Database ready"

# ── Done ─────────────────────────────────────────────

echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo -e "  Start the dev server:  ${BOLD}pnpm dev${NC}"
echo -e "  Dashboard:             ${BOLD}http://localhost:${CONFIGURED_PORT}${NC}"
echo ""
echo -e "${BLUE}Tip:${NC} The first user to sign up becomes the admin."
echo -e "${BLUE}Tip:${NC} Run ${BOLD}pnpm db:seed${NC} to load demo data."
echo ""
