#!/usr/bin/env bash
set -euo pipefail

# HITLaaS Self-Hosting Setup Wizard
# -----------------------------------

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'

DIR="$(cd "$(dirname "$0")/.." && pwd)"

info()  { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()    { echo -e "${GREEN}✓${NC}  $*"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
err()   { echo -e "${RED}✗${NC}  $*"; }

header() {
  echo ""
  echo -e "${BOLD}╔══════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║   HITLaaS Self-Hosting Setup Wizard  ║${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════╝${NC}"
  echo ""
}

# ── Helpers ──────────────────────────────────────────

prompt() {
  local var="$1" msg="$2" default="${3:-}"
  if [[ -n "$default" ]]; then
    read -rp "$(echo -e "${BLUE}?${NC}  ${msg} [${default}]: ")" val
    eval "$var=\"${val:-$default}\""
  else
    read -rp "$(echo -e "${BLUE}?${NC}  ${msg}: ")" val
    eval "$var=\"$val\""
  fi
}

prompt_secret() {
  local var="$1" msg="$2"
  read -srp "$(echo -e "${BLUE}?${NC}  ${msg}: ")" val
  echo ""
  eval "$var=\"$val\""
}

choose_connectivity() {
  echo ""
  echo -e "${BOLD}Choose a connectivity option:${NC}"
  echo "  1) Cloudflare Tunnel  (recommended – free, custom domain, fastest)"
  echo "  2) Tailscale Funnel   (easy, uses your Tailscale network)"
  echo "  3) Ngrok              (quick start, random URL on free tier)"
  echo "  4) None / Manual      (you handle port forwarding yourself)"
  echo ""
  read -rp "$(echo -e "${BLUE}?${NC}  Enter choice [1-4]: ")" choice
}

# ── Generate .env ────────────────────────────────────

generate_env() {
  local env_file="$DIR/.env"

  # Preserve existing values
  local existing_db_url="" existing_secret="" existing_github_id="" existing_github_secret=""
  if [[ -f "$env_file" ]]; then
    existing_db_url=$(grep '^DATABASE_URL=' "$env_file" 2>/dev/null | cut -d= -f2- || true)
    existing_secret=$(grep '^NEXTAUTH_SECRET=' "$env_file" 2>/dev/null | cut -d= -f2- || true)
    existing_github_id=$(grep '^AUTH_GITHUB_ID=' "$env_file" 2>/dev/null | cut -d= -f2- || true)
    existing_github_secret=$(grep '^AUTH_GITHUB_SECRET=' "$env_file" 2>/dev/null | cut -d= -f2- || true)
  fi

  local secret="${existing_secret:-$(openssl rand -base64 32)}"

  prompt NEXTAUTH_URL "Public URL for your HITLaaS instance" "${PUBLIC_URL:-http://localhost:3000}"

  cat > "$env_file" <<EOF
# HITLaaS Environment Configuration
# Generated by setup wizard on $(date -Iseconds)

DATABASE_URL=${existing_db_url:-postgresql://hitlaas:hitlaas_dev@db:5432/hitlaas}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXTAUTH_SECRET=${secret}
AUTH_GITHUB_ID=${existing_github_id}
AUTH_GITHUB_SECRET=${existing_github_secret}
CONNECTIVITY_METHOD=${CONNECTIVITY_METHOD}
EOF

  # Append connectivity-specific vars
  case "$CONNECTIVITY_METHOD" in
    cloudflare)
      echo "CLOUDFLARE_TUNNEL_TOKEN=${CF_TOKEN}" >> "$env_file"
      ;;
    tailscale)
      echo "TAILSCALE_AUTHKEY=${TS_KEY}" >> "$env_file"
      ;;
    ngrok)
      echo "NGROK_AUTHTOKEN=${NGROK_TOKEN}" >> "$env_file"
      [[ -n "${NGROK_DOMAIN:-}" ]] && echo "NGROK_DOMAIN=${NGROK_DOMAIN}" >> "$env_file"
      ;;
  esac

  ok "Generated .env"
}

# ── Generate docker-compose.override.yml ─────────────

generate_override() {
  local override="$DIR/docker-compose.override.yml"

  case "$CONNECTIVITY_METHOD" in
    cloudflare)
      cat > "$override" <<'EOF'
# Auto-generated by setup wizard – Cloudflare Tunnel
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    command: tunnel --no-autoupdate run
    env_file: .env
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}

  app:
    env_file: .env
EOF
      ;;
    tailscale)
      mkdir -p "$DIR/tailscale-config"
      cat > "$DIR/tailscale-config/serve.json" <<'EOF'
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "app.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://app:3000"
        }
      }
    }
  }
}
EOF
      cat > "$override" <<'EOF'
# Auto-generated by setup wizard – Tailscale Funnel
services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    hostname: hitlaas
    env_file: .env
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/serve.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun

  app:
    env_file: .env

volumes:
  tailscale-state:
EOF
      ;;
    ngrok)
      local ngrok_cmd="http app:3000 --log stdout"
      [[ -n "${NGROK_DOMAIN:-}" ]] && ngrok_cmd="http app:3000 --domain=${NGROK_DOMAIN} --log stdout"
      cat > "$override" <<EOF
# Auto-generated by setup wizard – Ngrok
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    command: ${ngrok_cmd}
    env_file: .env
    environment:
      NGROK_AUTHTOKEN: \${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

  app:
    env_file: .env
EOF
      ;;
    direct)
      cat > "$override" <<'EOF'
# Auto-generated by setup wizard – Direct / Manual
services:
  app:
    env_file: .env
EOF
      ;;
  esac

  ok "Generated docker-compose.override.yml"
}

# ── Connectivity setup ───────────────────────────────

setup_cloudflare() {
  CONNECTIVITY_METHOD="cloudflare"
  echo ""
  info "Cloudflare Tunnel Setup"
  info "Create a tunnel at https://one.dash.cloudflare.com → Networks → Tunnels"
  info "Set the tunnel's public hostname to point to http://app:3000"
  echo ""
  prompt_secret CF_TOKEN "Cloudflare Tunnel token"
  if [[ -z "$CF_TOKEN" ]]; then
    err "Token is required"; exit 1
  fi
  PUBLIC_URL=""
  prompt PUBLIC_URL "Your custom domain (e.g. https://hitlaas.example.com)"
}

setup_tailscale() {
  CONNECTIVITY_METHOD="tailscale"
  echo ""
  info "Tailscale Funnel Setup"
  info "Generate an auth key at https://login.tailscale.com/admin/settings/keys"
  info "Enable Funnel in your Tailscale ACL policy"
  echo ""
  prompt_secret TS_KEY "Tailscale auth key"
  if [[ -z "$TS_KEY" ]]; then
    err "Auth key is required"; exit 1
  fi
  PUBLIC_URL="https://hitlaas.<your-tailnet>.ts.net"
  warn "Your URL will be https://hitlaas.<tailnet-name>.ts.net"
}

setup_ngrok() {
  CONNECTIVITY_METHOD="ngrok"
  echo ""
  info "Ngrok Setup"
  info "Get your auth token at https://dashboard.ngrok.com/get-started/your-authtoken"
  echo ""
  prompt_secret NGROK_TOKEN "Ngrok auth token"
  if [[ -z "$NGROK_TOKEN" ]]; then
    err "Auth token is required"; exit 1
  fi
  prompt NGROK_DOMAIN "Custom domain (leave empty for random URL)" ""
  if [[ -n "$NGROK_DOMAIN" ]]; then
    PUBLIC_URL="https://${NGROK_DOMAIN}"
  else
    PUBLIC_URL="(will be shown after starting ngrok – check http://localhost:4040)"
    warn "Free ngrok URLs change on restart. Check http://localhost:4040/status for current URL."
  fi
}

setup_direct() {
  CONNECTIVITY_METHOD="direct"
  PUBLIC_URL="http://localhost:3000"
  warn "No tunnel configured. You'll need to handle port forwarding yourself."
}

# ── Test connectivity ────────────────────────────────

test_health() {
  echo ""
  info "Testing health endpoint..."
  if command -v curl &>/dev/null; then
    if curl -sf http://localhost:3000/api/health >/dev/null 2>&1; then
      ok "Health endpoint responding"
    else
      warn "Health endpoint not reachable (app may not be running yet)"
    fi
  fi
}

# ── Main ─────────────────────────────────────────────

header

# Check prerequisites
for cmd in docker; do
  if ! command -v "$cmd" &>/dev/null; then
    err "$cmd is required but not installed"
    exit 1
  fi
done

if docker compose version &>/dev/null; then
  ok "Docker Compose available"
else
  err "Docker Compose is required (docker compose plugin)"
  exit 1
fi

choose_connectivity

case "$choice" in
  1) setup_cloudflare ;;
  2) setup_tailscale ;;
  3) setup_ngrok ;;
  4) setup_direct ;;
  *) err "Invalid choice"; exit 1 ;;
esac

generate_env
generate_override

echo ""
echo -e "${BOLD}── Summary ──────────────────────────────${NC}"
echo -e "  Connectivity:  ${GREEN}${CONNECTIVITY_METHOD}${NC}"
echo -e "  Public URL:    ${GREEN}${PUBLIC_URL}${NC}"
echo -e "  Config files:  .env, docker-compose.override.yml"
echo ""

read -rp "$(echo -e "${BLUE}?${NC}  Start the stack now? [Y/n]: ")" start_now
if [[ "${start_now,,}" != "n" ]]; then
  info "Starting HITLaaS..."
  cd "$DIR"
  docker compose up -d
  echo ""
  ok "Stack is starting! Check logs with: docker compose logs -f"
  test_health
else
  info "Start manually with: docker compose up -d"
fi

echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo -e "API endpoint: ${BOLD}${PUBLIC_URL}${NC}"
echo ""
